{
	"id": "SUSE-SU-2020:14468-1",
	"modified": "2020-08-27T16:27:25Z",
	"published": "2020-08-27T16:27:25Z",
	"summary": "Security update for openvpn-openssl1",
	"details": "This update for openvpn-openssl1 fixes the following issues:\n\n- Fixed Out of bounds read on getaddrinfo() result (bsc#959714).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Server 11-SECURITY",
				"name": "openvpn-openssl1",
				"purl": "pkg:rpm/suse/openvpn-openssl1&distro=SUSE%20Linux%20Enterprise%20Server%2011-SECURITY"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.3.2-0.10.6.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"openvpn-openssl1": "2.3.2-0.10.6.1",
						"openvpn-openssl1-down-root-plugin": "2.3.2-0.10.6.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2020/suse-su-202014468-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/959714"
		}
	]
}
