{
	"id": "SUSE-SU-2020:0750-1",
	"modified": "2020-03-23T15:32:35Z",
	"published": "2020-03-23T15:32:35Z",
	"related": [
		"CVE-2019-18348"
	],
	"summary": "Security update for python36",
	"details": "This update for python36 fixes the following issues:\n\n- CVE-2019-18348: Fixed a CRLF injection via the host part \n  of the url passed to urlopen(). Now an InvalidURL exception \n  is raised (bsc#1155094).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Server 12 SP5",
				"name": "python36",
				"purl": "pkg:rpm/suse/python36&distro=SUSE%20Linux%20Enterprise%20Server%2012%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.10-4.9.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.10-4.9.1",
						"python36": "3.6.10-4.9.1",
						"python36-base": "3.6.10-4.9.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Server 12 SP5",
				"name": "python36-base",
				"purl": "pkg:rpm/suse/python36-base&distro=SUSE%20Linux%20Enterprise%20Server%2012%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.10-4.9.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.10-4.9.1",
						"python36": "3.6.10-4.9.1",
						"python36-base": "3.6.10-4.9.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Server for SAP Applications 12 SP5",
				"name": "python36",
				"purl": "pkg:rpm/suse/python36&distro=SUSE%20Linux%20Enterprise%20Server%20for%20SAP%20Applications%2012%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.10-4.9.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.10-4.9.1",
						"python36": "3.6.10-4.9.1",
						"python36-base": "3.6.10-4.9.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Server for SAP Applications 12 SP5",
				"name": "python36-base",
				"purl": "pkg:rpm/suse/python36-base&distro=SUSE%20Linux%20Enterprise%20Server%20for%20SAP%20Applications%2012%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.10-4.9.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.10-4.9.1",
						"python36": "3.6.10-4.9.1",
						"python36-base": "3.6.10-4.9.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2020/suse-su-20200750-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1155094"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-18348"
		}
	]
}
