{
	"id": "openSUSE-SU-2019:1166-1",
	"modified": "2019-04-05T11:28:57Z",
	"published": "2019-04-05T11:28:57Z",
	"related": [
		"CVE-2019-9917"
	],
	"summary": "Security update for znc",
	"details": "This update for znc to version 1.7.2 fixes the following issue:\n\nSecurity issue fixed: \n\n- CVE-2019-9917: Fixed an issue where due to invalid encoding znc was crashing (bsc#1130360).\n ",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Package Hub 12",
				"name": "znc",
				"purl": "pkg:rpm/suse/znc&distro=SUSE%20Package%20Hub%2012"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.7.2-bp150.2.3.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"znc": "1.7.2-bp150.2.3.1",
						"znc-devel": "1.7.2-bp150.2.3.1",
						"znc-lang": "1.7.2-bp150.2.3.1",
						"znc-perl": "1.7.2-bp150.2.3.1",
						"znc-python3": "1.7.2-bp150.2.3.1",
						"znc-tcl": "1.7.2-bp150.2.3.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Package Hub 12 SP2",
				"name": "znc",
				"purl": "pkg:rpm/suse/znc&distro=SUSE%20Package%20Hub%2012%20SP2"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.7.2-bp150.2.3.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"znc": "1.7.2-bp150.2.3.1",
						"znc-devel": "1.7.2-bp150.2.3.1",
						"znc-lang": "1.7.2-bp150.2.3.1",
						"znc-perl": "1.7.2-bp150.2.3.1",
						"znc-python3": "1.7.2-bp150.2.3.1",
						"znc-tcl": "1.7.2-bp150.2.3.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Package Hub 15",
				"name": "znc",
				"purl": "pkg:rpm/suse/znc&distro=SUSE%20Package%20Hub%2015"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.7.2-bp150.2.3.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"znc": "1.7.2-bp150.2.3.1",
						"znc-devel": "1.7.2-bp150.2.3.1",
						"znc-lang": "1.7.2-bp150.2.3.1",
						"znc-perl": "1.7.2-bp150.2.3.1",
						"znc-python3": "1.7.2-bp150.2.3.1",
						"znc-tcl": "1.7.2-bp150.2.3.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.0",
				"name": "znc",
				"purl": "pkg:rpm/opensuse/znc&distro=openSUSE%20Leap%2015.0"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.7.2-bp150.2.3.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"znc": "1.7.2-bp150.2.3.1",
						"znc-devel": "1.7.2-bp150.2.3.1",
						"znc-lang": "1.7.2-bp150.2.3.1",
						"znc-perl": "1.7.2-bp150.2.3.1",
						"znc-python3": "1.7.2-bp150.2.3.1",
						"znc-tcl": "1.7.2-bp150.2.3.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/NS4KDD2JHM2AY5AJHI5PL4TKUB5PG45U/#NS4KDD2JHM2AY5AJHI5PL4TKUB5PG45U"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1130360"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-9917"
		}
	]
}
