{
	"id": "SUSE-SU-2024:4285-1",
	"modified": "2024-12-11T08:30:20Z",
	"published": "2024-12-11T08:30:20Z",
	"related": [
		"CVE-2024-53907",
		"CVE-2024-53908"
	],
	"summary": "Security update for python-Django",
	"details": "This update for python-Django fixes the following issues:\n\n  - CVE-2024-53907: Fixed denial-of-service in django.utils.html.strip_tags() (bsc#1234232)\n  - CVE-2024-53908: Fixed SQL injection in HasKey(lhs, rhs) on Oracle (bsc#1234231)\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Package Hub 15 SP6",
				"name": "python-Django",
				"purl": "pkg:rpm/suse/python-Django&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Package%20Hub%2015%20SP6"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "4.2.11-150600.3.12.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python311-Django": "4.2.11-150600.3.12.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.6",
				"name": "python-Django",
				"purl": "pkg:rpm/opensuse/python-Django&distro=openSUSE%20Leap%2015.6"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "4.2.11-150600.3.12.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python311-Django": "4.2.11-150600.3.12.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20244285-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1234231"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1234232"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-53907"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-53908"
		}
	]
}
