{
	"id": "SUSE-SU-2024:1572-1",
	"modified": "2024-05-09T11:18:15Z",
	"published": "2024-05-09T11:18:15Z",
	"related": [
		"CVE-2024-34069"
	],
	"summary": "Security update for python-Werkzeug",
	"details": "This update for python-Werkzeug fixes the following issues:\n\n- CVE-2024-34069: Fixed a remote code execution through debugger when interacting with attacker controlled domain (bsc#1223979).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Public Cloud 12",
				"name": "python-Werkzeug",
				"purl": "purl:rpm/suse/python-Werkzeug&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Public%20Cloud%2012"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0.12.2-10.16.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-Werkzeug": "0.12.2-10.16.1",
						"python3-Werkzeug": "0.12.2-10.16.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20241572-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1223979"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-34069"
		}
	]
}
