{
	"id": "SUSE-SU-2024:3760-1",
	"modified": "2024-10-28T03:33:33Z",
	"published": "2024-10-28T03:33:33Z",
	"related": [
		"CVE-2024-9287"
	],
	"summary": "Security update for python3",
	"details": "This update for python3 fixes the following issues:\n\nSecurity fixes:\n\n- CVE-2024-9287: properly quote path names provided when creating a virtual environment (bsc#1232241)\n\nOther fixes:\n\n- Drop .pyc files from docdir for reproducible builds (bsc#1230906)\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Micro 5.1",
				"name": "python3",
				"purl": "purl:rpm/suse/python3&distro=SUSE%20Linux%20Enterprise%20Micro%205.1"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.15-150000.3.164.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.15-150000.3.164.1",
						"python3": "3.6.15-150000.3.164.1",
						"python3-base": "3.6.15-150000.3.164.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Micro 5.1",
				"name": "python3-core",
				"purl": "purl:rpm/suse/python3-core&distro=SUSE%20Linux%20Enterprise%20Micro%205.1"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.15-150000.3.164.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.15-150000.3.164.1",
						"python3": "3.6.15-150000.3.164.1",
						"python3-base": "3.6.15-150000.3.164.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20243760-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1230906"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1232241"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-9287"
		}
	]
}
