{
	"id": "openSUSE-SU-2021:0851-1",
	"modified": "2021-06-07T12:06:03Z",
	"published": "2021-06-07T12:06:03Z",
	"related": [
		"CVE-2020-29651"
	],
	"summary": "Security update for python-py",
	"details": "This update for python-py fixes the following issues:\n\n- CVE-2020-29651: Fixed regular expression denial of service in svnwc.py (bsc#1179805, bsc#1184505).\n\nThis update was imported from the SUSE:SLE-15-SP1:Update update project.",
	"affected": [
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.2",
				"name": "python-py",
				"purl": "pkg:rpm/opensuse/python-py&distro=openSUSE%20Leap%2015.2"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.8.1-lp152.2.6.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python2-py": "1.8.1-lp152.2.6.1",
						"python3-py": "1.8.1-lp152.2.6.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.2",
				"name": "python-py-test",
				"purl": "pkg:rpm/opensuse/python-py-test&distro=openSUSE%20Leap%2015.2"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.8.1-lp152.2.6.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python2-py": "1.8.1-lp152.2.6.1",
						"python3-py": "1.8.1-lp152.2.6.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/J5N5MI5XRBM5X46XPGTD3CVA6C5MMBQJ/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1179805"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1184505"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2020-29651"
		}
	]
}
