{
	"id": "openSUSE-SU-2018:1271-1",
	"modified": "2018-05-11T17:35:46Z",
	"published": "2018-05-11T17:35:46Z",
	"related": [
		"CVE-2016-1516",
		"CVE-2016-1517"
	],
	"summary": "Security update for opencv",
	"details": "This update for opencv fixes the following issues:\n\n- CVE-2016-1517: Fixed a denial of service (segfault) via vectors involving corrupt chunks (boo#1033150)\n- CVE-2016-1516: Fixed a double free issue that allows attackers to execute arbitrary code (boo#1033152).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Package Hub 12 SP3",
				"name": "opencv",
				"purl": "purl:rpm/suse/opencv&distro=SUSE%20Package%20Hub%2012%20SP3"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.1.0-5.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libopencv-qt56_3": "3.1.0-5.1",
						"libopencv3_1": "3.1.0-5.1",
						"opencv": "3.1.0-5.1",
						"opencv-devel": "3.1.0-5.1",
						"opencv-doc": "3.1.0-5.1",
						"opencv-qt5": "3.1.0-5.1",
						"opencv-qt5-devel": "3.1.0-5.1",
						"opencv-qt5-doc": "3.1.0-5.1",
						"python-opencv": "3.1.0-5.1",
						"python-opencv-qt5": "3.1.0-5.1",
						"python3-opencv": "3.1.0-5.1",
						"python3-opencv-qt5": "3.1.0-5.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Package Hub 12 SP3",
				"name": "opencv-qt5",
				"purl": "purl:rpm/suse/opencv-qt5&distro=SUSE%20Package%20Hub%2012%20SP3"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.1.0-5.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libopencv-qt56_3": "3.1.0-5.1",
						"libopencv3_1": "3.1.0-5.1",
						"opencv": "3.1.0-5.1",
						"opencv-devel": "3.1.0-5.1",
						"opencv-doc": "3.1.0-5.1",
						"opencv-qt5": "3.1.0-5.1",
						"opencv-qt5-devel": "3.1.0-5.1",
						"opencv-qt5-doc": "3.1.0-5.1",
						"python-opencv": "3.1.0-5.1",
						"python-opencv-qt5": "3.1.0-5.1",
						"python3-opencv": "3.1.0-5.1",
						"python3-opencv-qt5": "3.1.0-5.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/V4TPAQTE3H3ONZFHSSFH4J6PADW56LC3/#V4TPAQTE3H3ONZFHSSFH4J6PADW56LC3"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1033150"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1033152"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2016-1516"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2016-1517"
		}
	]
}
